name: seg_models
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - tensorflow==2.1.0
  - keras==2.3.1
  - keras-applications==1.0.8
  - pip
  - pip:
    - efficientnet==1.0.0
    - image-classifiers==1.0.0
    - albumentations
